### ISSUE TITLE
Any chance that XR_ENVIRONMENT_BLEND support can be listed?

### ISSUE THREAD

**Issue by Kimau** [KhronosGroup/OpenXR-Inventory#10]
The passthrough extension is listed and a huge help to us, but we were looking for which runtime and HW supported the more native approach of XR_ENVIRONMENT_BLEND_MODE_ALPHA_BLEND is there any data on this?

**Comment by rpavlik** [comment]
I did add this to the JSON schema, but there hasn't been really much of this data populated yet, and no report page for it either. You're welcome to contribute what you know: this is a "crowd-sourced" database, we figured "somebody will do this sooner or later, we may as well start it".

**Comment by rpavlik** [comment]
Fixed by #24
