### ISSUE TITLE
Unable to push changes to remote

### ISSUE THREAD

**Issue by kevinkyle** [KhronosGroup/OpenXR-Inventory#8]
Hi,
I am Kyle from HTC who is working on OpneXR.
I just could not find a way to push updates of our runtime json files.
It always show "remote: Permission to KhronosGroup/OpenXR-Inventory.git denied to"

Can someone help on this?

**Comment by rpavlik** [comment]
Make a pull request. You can't push directly to main, it's a protected branch.

**Comment by kevinkyle** [comment]
No, I wan't pushing directly to main.
I wanted to create a new branch and push it but the permission is denied.
Should anyone has the permission to push a new branch?

**Comment by kevinkyle** [comment]
Never mind. I just figured it out and please help to merge it. Thanks.

**Comment by rpavlik** [comment]
yep, you got it - you have to fork it. I've reviewed and set it to auto-merge when the CI passes.
